export const GET_PRODUCTS_BEGIN = 'GET_PRODUCTS_BEGIN';
export const GET_PRODUCTS_SUCCESS = 'GET_PRODUCTS_SUCCESS';
export const GET_PRODUCTS_ERROR = 'GET_PRODUCTS_ERROR';

export const UPDATE_FILTERS = 'UPDATE_FILTERS';
export const CLEAR_FILTERS = 'CLEAR_FILTERS';
export const FILTER_PRODUCTS = 'FILTER_PRODUCTS';

export const ADD_TO_ORDER = 'ADD_TO_ORDER';
export const CLEAR_ORDER = 'CLEAR_ORDER';
export const PLACE_ORDER = 'PLACE_ORDER';
